apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 31080
    protocol: TCP
    name: http
  - port: 9080
    nodePort: 31081
    protocol: TCP
    name: http-apigw
  - port: 443
    nodePort: 31443
    protocol: TCP
    name: https
  selector:
    app: nginx-ingress
